# Generated by Django 4.2.7 on 2023-11-28 22:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('healthApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor_specialties',
            name='Doctor_Medical_ID_Number',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='healthApp.doctor'),
        ),
    ]
