# Generated by Django 4.2.7 on 2023-11-28 23:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('healthApp', '0002_alter_doctor_specialties_doctor_medical_id_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor_specialties',
            name='id',
            field=models.BigAutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='doctor_specialties',
            name='Doctor_Medical_ID_Number',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='healthApp.doctor'),
        ),
        migrations.AddConstraint(
            model_name='doctor_specialties',
            constraint=models.UniqueConstraint(fields=('Doctor_Medical_ID_Number', 'Specialty'), name='Specialties_pk_constraint'),
        ),
    ]
