# Generated by Django 4.2.7 on 2023-11-30 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('healthApp', '0003_doctor_specialties_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='procedure',
            name='Procedure_ID',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
