# Generated by Django 4.2.7 on 2023-11-28 04:40

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='Address',
            field=models.CharField(default='No Address On Record', max_length=500),
        ),
        migrations.AddField(
            model_name='customuser',
            name='Age',
            field=models.IntegerField(default=25, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(150)]),
        ),
        migrations.AddField(
            model_name='customuser',
            name='Phone_num',
            field=models.CharField(default='9991113333', max_length=10, validators=[django.core.validators.MinLengthValidator(10)]),
        ),
    ]
