# Generated by Django 4.2.7 on 2023-11-28 04:56

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_customuser_address_customuser_age_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='healthID',
            field=models.CharField(default=111111117, max_length=9, unique=True, validators=[django.core.validators.RegexValidator(code='invalid_your_field', message='Only digits (0-9) are allowed.', regex='^[0-9]+$'), django.core.validators.MinLengthValidator(9)]),
            preserve_default=False,
        ),
    ]
